name:                adventofcode2023
version:             0.1.0.0
github:              "alexMoraes/advent-of-code"
license:             BSD-3-Clause
author:              "Alex Moraes"
maintainer:          "alexmoraes251@gmail.com"
copyright:           "2023 Alex Moraes"

extra-source-files:
- README.md
- CHANGELOG.md

data-dir: "inputs"
data-files:
- "**/*.txt"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/adventofcode2023#readme>

dependencies:
- base >= 4.7 && < 5
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  day01:
    main:                Main.hs
    source-dirs:         app/day01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

executables:
  day02:
    main:                Main.hs
    source-dirs:         app/day02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

# tests:
#   adventofcode2023-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - adventofcode2023
